spring:
  cloud:
    consul:
      discovery:
        instance_id: user-command
  rabbitmq:
    hostname: localhost
    port: 5672
    username: axon
    password: axon
  application:
    exchange: microservice
    queue: axon
    index: 1